language: node_js

node_js:
  - '0.12'

before_install:
  - 'npm install -g gulp coffee-script nodemon phantomjs istanbul'

after_success:
  - 'npm run coverage; bash <(curl -s https://codecov.io/bash)'

services:
  - mongodb
